In [1]:
import pandas as pd
import numpy as np

# Load Iris dataset (built-in, no download needed)
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df['species'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

In [2]:
# First look (Always do this)
print(df.head())
print(df.info())
print(df.describe())
print(df.shape)
print(df.dtypes)
print(df.isnull().sum()) # check missing values

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target species
0       0  setosa
1       0  setosa
2       0  setosa
3       0  setosa
4       0  setosa
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
 5   species            150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB
None
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000
mean            5.843333          3.057333           3.758000
std             0.828066          0.435866           1.765298
min             4.300000          2.000000           1.000000
25%             5.100000          2.800000           1.600000
50%             5.800000          3.000000           4.350000
75%             6.400000          3.300000           5.100000
max             7.900000          4.400000           6.900000

       petal width (cm)      target
count        150.000000  150.000000
mean           1.199333    1.000000
std            0.762238    0.819232
min            0.100000    0.000000
25%            0.300000    0.000000
50%            1.300000    1.000000
75%            1.800000    2.000000
max            2.500000    2.000000
(150, 6)
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
species                  str
dtype: object
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
species              0
dtype: int64

In [3]:
# Selecting data
df['sepal length (cm)']                 # Series (1 column)
df[['sepal length (cm)', 'species']]    # DataFrame (multiple coulmns)
df.iloc[0]                              # first row by position
df.loc[df['species'] == 'setosa']       # filter rows

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
5,5.4,3.9,1.7,0.4,0,setosa
6,4.6,3.4,1.4,0.3,0,setosa
7,5.0,3.4,1.5,0.2,0,setosa
8,4.4,2.9,1.4,0.2,0,setosa
9,4.9,3.1,1.5,0.1,0,setosa
10,5.4,3.7,1.5,0.2,0,setosa
11,4.8,3.4,1.6,0.2,0,setosa
12,4.8,3.0,1.4,0.1,0,setosa
13,4.3,3.0,1.1,0.1,0,setosa
14,5.8,4.0,1.2,0.2,0,setosa
15,5.7,4.4,1.5,0.4,0,setosa
16,5.4,3.9,1.3,0.4,0,setosa
17,5.1,3.5,1.4,0.3,0,setosa
18,5.7,3.8,1.7,0.3,0,setosa
19,5.1,3.8,1.5,0.3,0,setosa
20,5.4,3.4,1.7,0.2,0,setosa
21,5.1,3.7,1.5,0.4,0,setosa
22,4.6,3.6,1.0,0.2,0,setosa
23,5.1,3.3,1.7,0.5,0,setosa
24,4.8,3.4,1.9,0.2,0,setosa
25,5.0,3.0,1.6,0.2,0,setosa
26,5.0,3.4,1.6,0.4,0,setosa
27,5.2,3.5,1.5,0.2,0,setosa
28,5.2,3.4,1.4,0.2,0,setosa
29,4.7,3.2,1.6,0.2,0,setosa
30,4.8,3.1,1.6,0.2,0,setosa
31,5.4,3.4,1.5,0.4,0,setosa
32,5.2,4.1,1.5,0.1,0,setosa
33,5.5,4.2,1.4,0.2,0,setosa
34,4.9,3.1,1.5,0.2,0,setosa
35,5.0,3.2,1.2,0.2,0,setosa
36,5.5,3.5,1.3,0.2,0,setosa
37,4.9,3.6,1.4,0.1,0,setosa
38,4.4,3.0,1.3,0.2,0,setosa
39,5.1,3.4,1.5,0.2,0,setosa
40,5.0,3.5,1.3,0.3,0,setosa
41,4.5,2.3,1.3,0.3,0,setosa
42,4.4,3.2,1.3,0.2,0,setosa
43,5.0,3.5,1.6,0.6,0,setosa
44,5.1,3.8,1.9,0.4,0,setosa
45,4.8,3.0,1.4,0.3,0,setosa
46,5.1,3.8,1.6,0.2,0,setosa
47,4.6,3.2,1.4,0.2,0,setosa
48,5.3,3.7,1.5,0.2,0,setosa
49,5.0,3.3,1.4,0.2,0,setosa

In [4]:
# Creating columns
df['sepal_area'] = df['sepal length (cm)'] * df['sepal width (cm)']

In [5]:
# Groupby (powerful for EDA)
df.groupby('species') ['sepal length (cm)'].mean()
df.groupby('species').agg({
    'sepal length (cm)': ['mean', 'std'],
    'petal length (cm)': ['mean', 'std']
})

           sepal length (cm)           petal length (cm)
                        mean       std              mean       std
species
setosa                 5.006  0.352490             1.462  0.173664
versicolor             5.936  0.516171             4.260  0.469911
virginica              6.588  0.635880             5.552  0.551895

In [6]:
# Sorting
df.sort_values('sepal length (cm)', ascending=False).head()

# Value counts
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64